---
- name: Create folder on Windows
  hosts: all
  gather_facts: no

  collections:
    - henryorg.win_folder

  tasks:
    - name: Create folder
      ansible.windows.win_file:
        path: C:\Temp\FromAnsible
        state: directory
